insert into reservation.restaurant values(1,"KFC",200);
insert into reservation.restaurant values(2,"Mc Donalds",245);
insert into reservation.restaurant values(3,"Pizza Hut",156);
insert into reservation.restaurant values(4,"Dominos",300);
insert into reservation.restaurant values(5,"Spicy Andhra Restaurant",215);
insert into reservation.reserve_table values(1,"Large Family Table",12);
insert into reservation.reserve_table values(2,"4 Person Table",2);
insert into reservation.reserve_table values(3,"Family Table",6);
insert into reservation.reserve_table values(4,"Round 3 Person Table",1);
insert into reservation.reserve_table values(5,"Sky Pool Table",15);
insert into reservation.reserve_table values(6,"2 Person Table",17);
insert into reservation.reserve_table values(7,"16 Person Table",8);
insert into reservation.reserve_table values(8,"8 Table",10);
insert into reservation.reserve_table values(9,"12 Table",13);
insert into reservation.reserve_table values(10,"Candle Light Table",11);
insert into reservation.restaurant_table values(1,9);
insert into reservation.restaurant_table values(1,6);
insert into reservation.restaurant_table values(2,8);
insert into reservation.restaurant_table values(2,2);
insert into reservation.restaurant_table values(3,4);
insert into reservation.restaurant_table values(3,5);
insert into reservation.restaurant_table values(4,3);
insert into reservation.restaurant_table values(4,7);
insert into reservation.restaurant_table values(5,1);
insert into reservation.restaurant_table values(5,10);
insert into reservation.menu values(1,150,"Panner Pizza");
insert into reservation.menu values(2,170,"Non Veg Pizza");
insert into reservation.menu values(3,200,"Chicken Pizza");
insert into reservation.menu values(4,154,"Chicken dominator Pizza");
insert into reservation.menu values(5,150,"Cheesy Pizza");
insert into reservation.menu values(6,140,"Veg Extra Pizza");
insert into reservation.menu values(7,151,"Chicken Nudgets");
insert into reservation.menu values(8,145,"Finger Fries");
insert into reservation.menu values(9,120,"Veg King Burger");
insert into reservation.menu values(10,50,"Dosa");
insert into reservation.menu values(11,40,"Kadai Panner");
insert into reservation.menu values(12,70,"Roti and Non Gravy");
insert into reservation.menu values(13,170,"Chicken Wings");
insert into reservation.menu values(14,140,"Chicken Bucket");
insert into reservation.menu values(15,120,"Smoky Chicken");
insert into reservation.restaurant_menu values(1,13);
insert into reservation.restaurant_menu values(1,14);
insert into reservation.restaurant_menu values(1,15);
insert into reservation.restaurant_menu values(2,7);
insert into reservation.restaurant_menu values(2,8);
insert into reservation.restaurant_menu values(2,9);
insert into reservation.restaurant_menu values(3,1);
insert into reservation.restaurant_menu values(3,2);
insert into reservation.restaurant_menu values(3,3);
insert into reservation.restaurant_menu values(4,4);
insert into reservation.restaurant_menu values(4,5);
insert into reservation.restaurant_menu values(4,6);
insert into reservation.restaurant_menu values(5,10);
insert into reservation.restaurant_menu values(5,11);
insert into reservation.restaurant_menu values(5,12);

